name: CD-DOCKER

on:
  workflow_run:
    workflows: ["CI-DOCKER"]
    types:
      - completed

jobs:
  build:
    runs-on: node_46
    steps:
      - name: Xóa File .evn cũ
        run: sudo rm -rf .env

      - name: Tạo File .env mới
        run: |
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}" >> .env
          echo "ACCESS_TOKEN_EXPIRED=${{secrets.ACCESS_TOKEN_EXPIRED}}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}" >> .env
          echo "REFRESH_TOKEN_EXPIRED=${{secrets.REFRESH_TOKEN_EXPIRED}}" >> .env

      - name: Dừng container đang chạy
        run: sudo docker container stop cons-be_cyber_media || true
      - name: Xóa container
        run: sudo docker container remove cons-be_cyber_media || true
      - name: Xóa image cũ
        run: sudo docker image remove leminhquangdev/image-be_cyber_media:latest || true

      - name: Chạy lại docker compose
        run: sudo docker-compose up -d
